# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoTheUITestsWork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoTheUITestsWork

  target 'DoTheUITestsWorkTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'iOSSnapshotTestCase', '4.0.0'
  end

end
